### ISSUE TITLE
Split tests and write benchmarks

### ISSUE THREAD

**Issue by olehmell** [dappforce/subsocial-parachain#87]
### Move `integration-test` from Solochain
First, we will add `integration-test` to the parachain and make sure it passes with no issues.
- [x] #74

### Extract tests from `integration-tests` to pallets

**❕NOTE❕** Because tests have some cyclic dependencies, I've made a sub-create inside each pallet to house the tests, later on, we can refactor tests to remove cyclic dependencies and have the tests in the same pallet.
- [x] Posts tests #83 
- [x] Reactions tests #84 
- [x] Spaces tests #80 
- [x] Space follows tests #81 
- [x] Space ownership tests #82 

## Benchmarking
**❕NOTE❕** since tests lives in another create I can't include tests via `impl_benchmark_test_suite!` macro.
- [x] Posts benchmarks #100
- [x] Spaces benchmarks #96 
- [x] Space follow benchmarks #113 
- [x] Space ownership benchmarks  #121
- [x] Reactions benchmarks #98 
- [x] Roles benchmarks #126

**Comment by F3Joule** [comment]
Needs review from @siman and @F3Joule
